default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: 
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: comodo_backend_dev
test:
  <<: *default
  database: comodo_backend_test

production:
  <<: *default
  database: comodo_backend_prod
  username: comodo_backend
  password: <%= ENV["COMODO_BACKEND_DATABASE_PASSWORD"] %>